### ISSUE TITLE
https://tracer.finance/tokens does not point to this repository

### ISSUE THREAD

**Issue by TomAFrench** [dospore/tracer-balancer-token-list#2]
https://tracer.finance/tokens currently reports token logoURIs in the form `https://raw.githubusercontent.com/dospore/tracer-balancer-token-list/master/assets/btc_long.png` whereas [tokens.json](https://github.com/dospore/tracer-balancer-token-list/blob/master/tokens.json) reports them (accurately) as `https://raw.githubusercontent.com/dospore/tracer-balancer-token-list/master/assets/L-BTC.png`

This results in broken logos for any frontend using the https://tracer.finance/tokens list. Ideally https://tracer.finance/tokens should just mirror what's in tokens.json

**Comment by dospore** [comment]
> https://tracer.finance/tokens currently reports token logoURIs in the form `https://raw.githubusercontent.com/dospore/tracer-balancer-token-list/master/assets/btc_long.png` whereas [tokens.json](https://github.com/dospore/tracer-balancer-token-list/blob/master/tokens.json) reports them (accurately) as `https://raw.githubusercontent.com/dospore/tracer-balancer-token-list/master/assets/L-BTC.png`
> 
> This results in broken logos for any frontend using the https://tracer.finance/tokens list. Ideally https://tracer.finance/tokens should just mirror what's in tokens.json

thanks for this, have routed tracer.finance/tokens directly to this repo's token list

**Comment by TomAFrench** [comment]
Awesome, this is displaying properly on the staging Balancer UI now. Many thanks.
